name: Update Latest Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete Existing Latest Release
        run: |
          RELEASE_ID=$(gh release list --json id,name | jq -r '.[] | select(.name == "latest") | .id')
          if [ -n "$RELEASE_ID" ]; then
            gh release delete "latest" --yes
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Existing Latest Tag
        run: |
          if git rev-parse "latest" >/dev/null 2>&1; then
            git tag -d "latest"
            git push origin :refs/tags/latest
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Latest Tag
        run: |
          git tag latest
          git push origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Latest Release
        run: |
          gh release create "latest" \
            --title "latest" \
            --notes "Automatically updated to the latest commit on ${{ github.sha }}" \
            --target ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}