name: Update Latest Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug GH_PAT Secret
      - name: Debug GH_PAT
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is empty or not set."
            exit 1 # Fail the workflow if GH_PAT is not set
          else
            echo "GH_PAT is set."
          fi

      # Step 3: Get the latest release or create one if it doesn't exist
      - name: Get or Create Release
        id: get_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          draft: false
          prerelease: false
          token: ${{ secrets.GH_PAT }} # Use the PAT instead of GITHUB_TOKEN

      # Step 4: Debug Upload URL
      - name: Debug Upload URL
        run: |
          echo "Upload URL: ${{ steps.get_release.outputs.upload_url }}"
          if [ -z "${{ steps.get_release.outputs.upload_url }}" ]; then
            echo "Upload URL is missing. Check the previous step for errors."
            exit 1
          fi

      # Step 5: Archive the source code
      - name: Archive source code
        run: |
          git archive --format=zip --output=source-code.zip HEAD

      # Step 6: Upload the source code to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./source-code.zip
          asset_name: source-code.zip
          asset_content_type: application/zip
          token: ${{ secrets.GH_PAT }} # Explicitly use the PAT for authentication